language: ruby
rvm:
 - 1.8.7
 - 2.0.0

script: "rake spec"

branches:
  only:
      - master
      - dev
      - /^issues\/.*$/

notifications:
  email:
    - arusso@berkeley.edu

env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"

matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
